### ISSUE TITLE
[BUG] `pdm generate-schema` in readme does not work

### ISSUE THREAD

**Issue by chirino** [road-core/service#180]
# Bug Description

Readme states you can run `pdm generate-schema`.  This fails for me:

```
pdm generate-schema 
Running <task generate-schema>: ['pdm', 'run', 'make', 'schema']

python scripts/generate_openapi_schema.py docs/openapi.json
Failed to load config file olsconfig.yaml: [Errno 2] No such file or directory: 'olsconfig.yaml'
Traceback (most recent call last):
  File "/Users/chirino/sandbox/road-core-service/ols/utils/config.py", line 114, in reload_from_yaml_file
    with open(config_file, encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'olsconfig.yaml'

Traceback (most recent call last):
  File "/Users/chirino/sandbox/road-core-service/scripts/generate_openapi_schema.py", line 19, in <module>
    config.reload_from_yaml_file(cfg_file)
  File "/Users/chirino/sandbox/road-core-service/ols/utils/config.py", line 114, in reload_from_yaml_file
    with open(config_file, encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'olsconfig.yaml'
make: *** [schema] Error 1
```

**Comment by tisnik** [comment]
Ah thanks, I'm on it!
